apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Кажемо Kustomize взяти чистий каркас додатка з бази
resources:
  - ../../app-base

patches:
  - target:
      kind: Deployment
      name: jobmatch-api-deployment
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/build_id
        value: "dev-v1"
