apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jobmatch-dev-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Dezmag/jobmatch-project.git' # Твій репозиторій
    targetRevision: HEAD # Стежимо за останньою версією в main
    path: platform/gitops/environments/dev # Вказуємо шлях до маніфестів DEV
  destination:
    server: 'https://kubernetes.default.svc' # Деплоїмо в цей же локальний кластер
    namespace: default
  syncPolicy:
    automated:
      prune: true # Автоматично видаляти ресурси, якщо вони зникли з Git
      selfHeal: true # Якщо хтось руками щось змінить в кластері — ArgoCD поверне як було в Git
