apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../app-base

# Додаємо префікс до назви всіх ресурсів у цьому оточенні
namePrefix: staging-

patches:
  - target:
      kind: Deployment
      name: jobmatch-api-deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "staging"
