name: CI Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Критично важливий DevOps-крок: переводимо назву в нижній регістр
      - name: Downcase repository name
        run: |
          echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Збірка та пуш БЕКЕНДУ (API) з маленької літери
      - name: Build and push API Image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          target: api
          push: true
          tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}/job-match-api:latest

      # Збірка та пуш ФРОНТЕНДУ (Web) з маленької літери
      - name: Build and push Web Image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          target: web
          push: true
          tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}/job-match-web:latest
